#!/usr/bin/env sh

curl https://nixos.org/nix/install | sh

touch "${HOME}"/.local.sh
touch "${HOME}"/.company.env

git config --global commit.template $(pwd)/git/git-message.txt
git config --global --add core.excludesfile $(pwd)/git/.gitignore
$(pwd)/git/git-alias-setting.sh

[ -f "${HOME}"/.zshrc ] && rm "${HOME}"/.zshrc || true
ln -s $(pwd)/zsh-set/.zshrc "${HOME}"/.zshrc
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

mkdir -p "${HOME}"/.config/nvim
[ -f "${HOME}"/.config/nvim/init.vim ] && rm "${HOME}"/.config/nvim/init.vim || true
ln -s $(pwd)/nvim-set/config/nvim/init.vim "${HOME}"/.config/nvim/init.vim
$(pwd)/nvim-set/install.sh

# terminal
nix-env -i direnv neovim silver-searcher
# language
nix-env -i cmake clang-tools llvm gcc racket go
