#!/usr/bin/env sh

curl https://nixos.org/nix/install | sh

ln -s $(pwd)/home.nix ${HOME}/.config/nixpkgs/home.nix

git config --global commit.template "$(pwd)"/git-message.txt

# generate current machine information
echo "{ operatingSystem = \"$(uname -v | awk '{ print $1 }' | sed 's/#.*-//')\"; }" > machine.nix

# install zsh plugin: k
# FIXME ?git clone https://github.com/supercrabtree/k $ZSH_CUSTOM/plugins/k
