set expandtab
set tabstop=4
retab
set shiftwidth=4
set undofile
set cursorline
" show line number
set number
set nolist
set listchars=tab:→\ ,trail:•
set list
" open from last editing point
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

let g:ackprg = 'ag --vimgrep'

" allow mouse action
set mouse=a
" allow virtual editing
set virtualedit=all

" Theme
syntax enable
"let g:solarized_termcolors=256
"colorscheme solarized
"colorscheme oldbook
"colorscheme distilled
colorscheme nord
set termguicolors

" Mapping key
"" file true
map <C-n> :NERDTreeToggle<CR>
"" Improve window switching, remove <C-W>
map <C-J> <C-W><C-J>
map <C-K> <C-W><C-K>
map <C-L> <C-W><C-L>
map <C-H> <C-W><C-H>

" Ignore up/low case
cab W w
cab Wq wq
cab wQ wq
cab WQ wq
cab Q q

""""""""""""""""" COC """""""""""""""""""""

" TextEdit might fail if hidden is not set.
set hidden

" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Give more space for displaying messages.
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" GoTo code navigation.
map <C-b> <Plug>(coc-definition)
map <C-r> <Plug>(coc-rename)
